using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ContosoUniversity.Migrations
{
    /// <inheritdoc />
    public partial class DepartmentSP : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE PROCEDURE dbo.Department_Insert
                    @Name NVARCHAR(50),
                    @Budget MONEY,
                    @StartDate DATETIME,
                    @InstructorId INT = NULL
                AS
                BEGIN
                    SET NOCOUNT ON;

                    -- Fixed column mapping: Primary Key [Id] is auto-generated by identity, 
                    -- so we only insert the actual foreign key [@InstructorId] here.
                    INSERT [dbo].[Department]([Name], [Budget], [StartDate], [InstructorId])
                    VALUES (@Name, @Budget, @StartDate, @InstructorId);
            
                    DECLARE @InsertedId INT;
                    SELECT @InsertedId = [Id]
                    FROM [dbo].[Department]
                    WHERE @@ROWCOUNT > 0 AND [Id] = SCOPE_IDENTITY();
            
                    -- Return the newly generated identity ID back to EF Core
                    SELECT t0.[Id]
                    FROM [dbo].[Department] AS t0
                    WHERE @@ROWCOUNT > 0 AND t0.[Id] = @InsertedId;
                END
            ");

            migrationBuilder.Sql(@"
                CREATE PROCEDURE dbo.Department_Update
                    @Id INT,
                    @Name NVARCHAR(50),
                    @Budget MONEY,
                    @StartDate DATETIME,
                    @InstructorId INT = NULL
                AS
                BEGIN
                    SET NOCOUNT ON;

                    UPDATE [dbo].[Department]
                    SET [Name] = @Name, 
                        [Budget] = @Budget, 
                        [StartDate] = @StartDate, 
                        [InstructorId] = @InstructorId
                    WHERE [Id] = @Id;
                END
            ");

            migrationBuilder.Sql(@"
                CREATE PROCEDURE dbo.Department_Delete
                    @Id INT
                AS
                BEGIN
                    SET NOCOUNT ON;

                    DELETE FROM [dbo].[Department]
                    WHERE [Id] = @Id;
                END
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP PROCEDURE IF EXISTS dbo.Department_Insert;");
            migrationBuilder.Sql("DROP PROCEDURE IF EXISTS dbo.Department_Update;");
            migrationBuilder.Sql("DROP PROCEDURE IF EXISTS dbo.Department_Delete;");
        }
    }
}
